### 회원가입
PUT http://localhost:8080/api/member/register
Content-Type: application/json

{
  "email" : "admin@naver.com",
  "password" : "1234",
  "address" : "경기도",
  "name" : "lee",
  "phoneNumber" : "010-1234-1234",
  "role": "USER"
}

### 로그인
POST localhost:8080/api/member/login?email=admin@naver.com&password=1234
Content-Type: application/x-www-form-urlencoded

### 로그인
POST localhost:8080/api/member/login
Content-Type: application/json

{
  "email" : "user",
  "password" : "dfb3ed2f-0b4e-4b64-9c8f-1afe0b519eb3"
}