### 제품 등록
PUT http://localhost:8080/api/product/add
Content-Type: application/json

{
    "name" : "스피커",
  "cnt" : 5,
  "mainImage" : "speak.jpg",
  "price": 10000,
  "description": "이 스피커는 스피커 입니다."
}

### 제품 조회
GET http://localhost:8080/api/product


### 제품 삭제
DELETE http://localhost:8080/api/product/delete/1